FROM adoptopenjdk:11-jre-hotspot-focal

MAINTAINER 罗俊平 591402399@qq.com

COPY target/ljp-client-9081.jar /application/ljp-client-9081.jar

EXPOSE 9081

ENTRYPOINT ['java', '-jar', '/application/ljp-client-9081.jar']
